name: "Newt - Pangolin Tunnels"
description: "Secure remote access with Pangolin tunnels."
maintainer: Alex Moras <alex@codesix.net>
url: https://docs.fossorial.io
version: "0.2.0"
slug: "newt"
boot: auto
init: false
arch:
  - aarch64
  - amd64
startup: services
hassio_api: true
options:
  id: ""
  secret: ""
  endpoint: ""
schema:
  id: str
  secret: str
  endpoint: str

